--This Insert gonna set the data for the Country(Countries) table.
insert into Countries(Name,isoCode,Population)
      values('Albania', 'ALB', '2775634')
insert into Countries(Name,isoCode,Population)
      values('Algeria', 'DZA', '44903225')
insert into Countries(Name,isoCode,Population)
      values('American Samoa', 'ASM', '44273')
insert into Countries(Name,isoCode,Population)
      values('Andorra', 'AND', '79824')
insert into Countries(Name,isoCode,Population)
      values('Angola', 'AGO', '35588987')
insert into Countries(Name,isoCode,Population)
      values('Antigua and Barbuda', 'ATG', '93763')
insert into Countries(Name,isoCode,Population)
      values('Argentina', 'ARG', '46234830')
insert into Countries(Name,isoCode,Population)
      values('Armenia', 'ARM', '2780469')
insert into Countries(Name,isoCode,Population)
      values('Aruba', 'ABW', '106445')
insert into Countries(Name,isoCode,Population)
      values('Australia', 'AUS', '25978935')
insert into Countries(Name,isoCode,Population)
      values('Austria', 'AUT', '9042528')
insert into Countries(Name,isoCode,Population)
      values('Azerbaijan', 'AZE', '10175016')
insert into Countries(Name,isoCode,Population)
      values('Bahamas, The', 'BHS', '409984')
insert into Countries(Name,isoCode,Population)
      values('Bahrain', 'BHR', '1472233')
insert into Countries(Name,isoCode,Population)
      values('Bangladesh', 'BGD', '171186372')
insert into Countries(Name,isoCode,Population)
      values('Barbados', 'BRB', '281635')
insert into Countries(Name,isoCode,Population)
      values('Belarus', 'BLR', '9208701')
insert into Countries(Name,isoCode,Population)
      values('Belgium', 'BEL', '11669446')
insert into Countries(Name,isoCode,Population)
      values('Belize', 'BLZ', '405272')
insert into Countries(Name,isoCode,Population)
      values('Benin', 'BEN', '13352864')
insert into Countries(Name,isoCode,Population)
      values('Bermuda', 'BMU', '63532')
insert into Countries(Name,isoCode,Population)
      values('Bhutan', 'BTN', '782455')
insert into Countries(Name,isoCode,Population)
      values('Bolivia', 'BOL', '12224110')
insert into Countries(Name,isoCode,Population)
      values('Bosnia and Herzegovina', 'BIH', '3233526')
insert into Countries(Name,isoCode,Population)
      values('Botswana', 'BWA', '2630296')
insert into Countries(Name,isoCode,Population)
      values('Brazil', 'BRA', '215313498')
insert into Countries(Name,isoCode,Population)
      values('British Virgin Islands', 'VGB', '31305')
insert into Countries(Name,isoCode,Population)
      values('Brunei Darussalam', 'BRN', '449002')
insert into Countries(Name,isoCode,Population)
      values('Bulgaria', 'BGR', '6465097')
insert into Countries(Name,isoCode,Population)
      values('Burkina Faso', 'BFA', '22673762')
insert into Countries(Name,isoCode,Population)
      values('Burundi', 'BDI', '12889576')
insert into Countries(Name,isoCode,Population)
      values('Cabo Verde', 'CPV', '593149')
insert into Countries(Name,isoCode,Population)
      values('Cambodia', 'KHM', '16767842')
insert into Countries(Name,isoCode,Population)
      values('Cameroon', 'CMR', '27914536')
insert into Countries(Name,isoCode,Population)
      values('Canada', 'CAN', '38929902')
insert into Countries(Name,isoCode,Population)
      values('Cayman Islands', 'CYM', '68706')
insert into Countries(Name,isoCode,Population)
      values('Central African Republic', 'CAF', '5579144')
insert into Countries(Name,isoCode,Population)
      values('Chad', 'TCD', '17723315')
insert into Countries(Name,isoCode,Population)
      values('Channel Islands', 'CHI', '174079')
insert into Countries(Name,isoCode,Population)
      values('Chile', 'CHL', '19603733')
insert into Countries(Name,isoCode,Population)
      values('China', 'CHN', '1412175000')
insert into Countries(Name,isoCode,Population)
      values('Colombia', 'COL', '51874024')
insert into Countries(Name,isoCode,Population)
      values('Comoros', 'COM','836774')
insert into Countries(Name,isoCode,Population)
      values('Congo, Dem. Rep.', 'COD', '99010212')
insert into Countries(Name,isoCode,Population)
      values('Congo, Rep.', 'COG', '5970424')
insert into Countries(Name,isoCode,Population)
      values ('Costa Rica', 'CRI', '5180829')
insert into Countries(Name,isoCode,Population)
      values('Cote d''Ivoire', 'CIV', '28160542')
insert into Countries(Name,isoCode,Population)
      values('Croatia', 'HRV', '3854000')
insert into Countries(Name,isoCode,Population)
      values('Cuba', 'CUB', '11212191')
insert into Countries(Name,isoCode,Population)
      values('Curacao', 'CUW', '149996')
insert into Countries(Name,isoCode,Population)
      values('Cyprus', 'CYP', '1251488')
insert into Countries(Name,isoCode,Population)
      values('Czechia', 'CZE', '10526073')
insert into Countries(Name,isoCode,Population)
      values('Denmark', 'DNK', '5903037')
insert into Countries(Name,isoCode,Population)
      values('Djibouti', 'DJI', '1120849')
insert into Countries(Name,isoCode,Population)
      values('Dominica', 'DMA', '72737')
insert into Countries(Name,isoCode,Population)
      values('Dominican Republic', 'DOM', '11228821')
insert into Countries(Name,isoCode,Population)
      values('Ecuador', 'ECU', '18001000')
insert into Countries(Name,isoCode,Population)
      values('Egypt, Arab Rep.', 'EGY', '110990103')
insert into Countries(Name,isoCode,Population)
      values('El Salvador', 'SLV', '6336392')
insert into Countries(Name,isoCode,Population)
      values('Equatorial Guinea', 'GNQ', '1674908')
insert into Countries(Name,isoCode,Population)
      values('Eritrea', 'ERI', '3684032')
insert into Countries(Name,isoCode,Population)
      values('Estonia', 'EST', '1344768')
insert into Countries(Name,isoCode,Population)
      values('Eswatini', 'SWZ', '1201670')
insert into Countries(Name,isoCode,Population)
      values('Ethiopia', 'ETH', '123379924')
insert into Countries(Name,isoCode,Population)
      values('Faroe Islands', 'FRO', '53090')
insert into Countries(Name,isoCode,Population)
      values('Fiji', 'FJI', '929766')
insert into Countries(Name,isoCode,Population)
      values('Finland', 'FIN', '5556880')
insert into Countries(Name,isoCode,Population)
      values('France', 'FRA', '67935660')
insert into Countries(Name,isoCode,Population)
      values('French Polynesia', 'PYF', '306279')
insert into Countries(Name,isoCode,Population)
      values('Gambia, The', 'GMB', '2705992')
insert into Countries(Name,isoCode,Population)
      values('Georgia', 'GEO', '3712502')
insert into Countries(Name,isoCode,Population)
      values('Germany', 'DEU', '84079811')
insert into Countries(Name,isoCode,Population)
      values('Ghana', 'GHA', '33475870')
insert into Countries(Name,isoCode,Population)
      values('Gibraltar', 'GIB', '32649')
insert into Countries(Name,isoCode,Population)
      values('Greece', 'GRC', '10566531')
insert into Countries(Name,isoCode,Population)
      values('Greenland', 'GRL', '56661')
insert into Countries(Name,isoCode,Population)
      values('Grenada', 'GRD', '125438')
insert into Countries(Name,isoCode,Population)
      values('Guam', 'GUM', '171774')
insert into Countries(Name,isoCode,Population)
      values('Guatemala', 'GTM', '17357886')
insert into Countries(Name,isoCode,Population)
      values('Guinea', 'GIN', '13859341')
insert into Countries(Name,isoCode,Population)
      values('Guinea-Bissau', 'GNB', '2105566')
insert into Countries(Name,isoCode,Population)
      values('Guyana', 'GUY', '808726')
insert into Countries(Name,isoCode,Population)
      values('Haiti', 'HTI', '11584996')
insert into Countries(Name,isoCode,Population)
      values('Honduras', 'HND', '10432860')
insert into Countries(Name,isoCode,Population)
      values('Hong Kong SAR, China', 'HKG', '7346100')
insert into Countries(Name,isoCode,Population)
      values('Hungary', 'HUN', '9683505')
insert into Countries(Name,isoCode,Population)
      values('Iceland', 'ISL', '381900')
insert into Countries(Name,isoCode,Population)
      values('India', 'IND', '1417173173')
insert into Countries(Name,isoCode,Population)
      values('Indonesia', 'IDN', '275501339')
insert into Countries(Name,isoCode,Population)
      values('Iran, Islamic Rep.', 'IRN', '88550570')
insert into Countries(Name,isoCode,Population)
      values('Iraq', 'IRQ', '44496122')
insert into Countries(Name,isoCode,Population)
      values('Ireland', 'IRL', '5086988')
insert into Countries(Name,isoCode,Population)
      values('Isle of Man', 'IMN', '84519')
insert into Countries(Name,isoCode,Population)
      values('Israel', 'ISR', '9550600')
insert into Countries(Name,isoCode,Population)
      values('Italy', 'ITA', '58856847')
insert into Countries(Name,isoCode,Population)
      values('Jamaica', 'JAM', '2827377')
insert into Countries(Name,isoCode,Population)
      values('Japan', 'JPN', '125124989')
insert into Countries(Name,isoCode,Population)
      values('Jordan', 'JOR', '11285869')
insert into Countries(Name,isoCode,Population)
      values('Kazakhstan', 'KAZ', '19621972')
insert into Countries(Name,isoCode,Population)
      values('Kenya', 'KEN', '54027487')
insert into Countries(Name,isoCode,Population)
      values('Kiribati', 'KIR', '131232')
insert into Countries(Name,isoCode,Population)
      values('Korea, Dem. People''s Rep.', 'PRK', '26069416')
insert into Countries(Name,isoCode,Population)
      values('Korea, Rep.', 'KOR', '51628117')
insert into Countries(Name,isoCode,Population)
      values('Kosovo', 'XKX', '1761985')
insert into Countries(Name,isoCode,Population)
      values('Kuwait', 'KWT', '4268873')
insert into Countries(Name,isoCode,Population)
      values('Kyrgyz Republic', 'KGZ', '6803300')
insert into Countries(Name,isoCode,Population)
      values('Lao PDR', 'LAO', '7529475')
insert into Countries(Name,isoCode,Population)
      values('Latvia', 'LVA', '1883379')
insert into Countries(Name,isoCode,Population)
      values('Lebanon', 'LBN', '5489739')
insert into Countries(Name,isoCode,Population)
      values('Lesotho', 'LSO', '2305825')
insert into Countries(Name,isoCode,Population)
      values('Liberia', 'LBR', '5302681')
insert into Countries(Name,isoCode,Population)
      values('Libya', 'LBY', '6812341')
insert into Countries(Name,isoCode,Population)
      values('Liechtenstein', 'LIE', '39327')
insert into Countries(Name,isoCode,Population)
      values('Lithuania', 'LTU', '2833000')
insert into Countries(Name,isoCode,Population)
      values('Luxembourg', 'LUX', '650774')
insert into Countries(Name,isoCode,Population)
      values('Macao SAR, China', 'MAC', '695168')
insert into Countries(Name,isoCode,Population)
      values('Macao SAR, China', 'MAC', '695168')
insert into Countries(Name,isoCode,Population)
      values('Malawi', 'MWI', '20405317')
insert into Countries(Name,isoCode,Population)
      values('Malaysia', 'MYS', '33938221')
insert into Countries(Name,isoCode,Population)
      values('Maldives', 'MDV', '523787')
insert into Countries(Name,isoCode,Population)
      values('Mali', 'MLI', '22593590')
insert into Countries(Name,isoCode,Population)
      values('Malta', 'MLT', '523417')
insert into Countries(Name,isoCode,Population)
      values('Marshall Islands', 'MHL', '41569')
insert into Countries(Name,isoCode,Population)
      values('Mauritania', 'MRT', '4736139')
insert into Countries(Name,isoCode,Population)
      values('Mauritius', 'MUS', '1262523')
insert into Countries(Name,isoCode,Population)
      values('Mexico', 'MEX', '127504125')
insert into Countries(Name,isoCode,Population)
      values('Micronesia, Fed. Sts.', 'FSM', '114164')
insert into Countries(Name,isoCode,Population)
      values('Moldova', 'MDA', '2592477')
insert into Countries(Name,isoCode,Population)
      values('Monaco', 'MCO', '36469')
insert into Countries(Name,isoCode,Population)
      values('Mongolia', 'MNG', '3398366')
insert into Countries(Name,isoCode,Population)
      values('Montenegro', 'MNE', '616159')
insert into Countries(Name,isoCode,Population)
      values('Morocco', 'MAR', '37457971')
insert into Countries(Name,isoCode,Population)
      values('Mozambique', 'MOZ', '32969518')
insert into Countries(Name,isoCode,Population)
      values('Myanmar', 'MMR', '54179306')
insert into Countries(Name,isoCode,Population)
      values('Namibia', 'NAM', '2567012')
insert into Countries(Name,isoCode,Population)
      values('Nauru', 'NRU', '12668')
insert into Countries(Name,isoCode,Population)
      values('Nepal', 'NPL','30547580')
insert into Countries(Name,isoCode,Population)
      values('Netherlands', 'NLD', '17703090')
insert into Countries(Name,isoCode,Population)
      values('New Caledonia', 'NCL', '276780')
insert into Countries(Name,isoCode,Population)
      values('New Zealand', 'NZL', '5124100')
insert into Countries(Name,isoCode,Population)
      values('Nicaragua', 'NIC', '6948392')
insert into Countries(Name,isoCode,Population)
      values('Niger', 'NER', '26207977')
insert into Countries(Name,isoCode,Population)
      values('Nigeria', 'NGA', '218541212')
insert into Countries(Name,isoCode,Population)
      values('North Macedonia', 'MKD', '2057679')
insert into Countries(Name,isoCode,Population)
      values('Northern Mariana Islands', 'MNP', '49551')
insert into Countries(Name,isoCode,Population)
      values('Norway', 'NOR', '5457127')
insert into Countries(Name,isoCode,Population)
      values('Oman', 'OMN', '4576298')
insert into Countries(Name,isoCode,Population)
      values('Pakistan', 'PAK', '235824862')
insert into Countries(Name,isoCode,Population)
      values('Palau', 'PLW', '18055')
insert into Countries(Name,isoCode,Population)
      values('Panama', 'PAN', '4408581')
insert into Countries(Name,isoCode,Population)
      values('Papua New Guinea', 'PNG', '10142619')
insert into Countries(Name,isoCode,Population)
      values('Paraguay', 'PRY', '6780744')
insert into Countries(Name,isoCode,Population)
      values('Peru', 'PER', '34049588')
insert into Countries(Name,isoCode,Population)
      values('Philippines', 'PHL', '115559009')
insert into Countries(Name,isoCode,Population)
      values('Poland', 'POL', '37561599')
insert into Countries(Name,isoCode,Population)
      values('Portugal', 'PRT', '10379007')
insert into Countries(Name,isoCode,Population)
      values('Puerto Rico', 'PRI', '3221789')
insert into Countries(Name,isoCode,Population)
      values('Qatar', 'QAT', '2695122')
insert into Countries(Name,isoCode,Population)
      values('Romania', 'ROU', '18956666')
insert into Countries(Name,isoCode,Population)
      values('Russian Federation', 'RUS', '143555736')
insert into Countries(Name,isoCode,Population)
      values('Rwanda', 'RWA', '13776698')
insert into Countries(Name,isoCode,Population)
      values('Samoa', 'WSM', '222382')
insert into Countries(Name,isoCode,Population)
      values('San Marino', 'SMR', '33660')
insert into Countries(Name,isoCode,Population)
      values('Sao Tome and Principe', 'STP', '227380')
insert into Countries(Name,isoCode,Population)
      values('Saudi Arabia', 'SAU', '36408820')
insert into Countries(Name,isoCode,Population)
      values('Senegal', 'SEN', '17316449')
insert into Countries(Name,isoCode,Population)
      values('Serbia', 'SRB', '6760087')
insert into Countries(Name,isoCode,Population)
      values('Seychelles', 'SYC', '100060')
insert into Countries(Name,isoCode,Population)
      values('Sierra Leone', 'SLE', '8605718')
insert into Countries(Name,isoCode,Population)
      values('Singapore', 'SGP', '5637022')
insert into Countries(Name,isoCode,Population)
      values('Sint Maarten (Dutch part)', 'SXM', '43389')
insert into Countries(Name,isoCode,Population)
      values('Slovak Republic', 'SVK', '5431752')
insert into Countries(Name,isoCode,Population)
      values('Slovenia', 'SVN', '2108732')
insert into Countries(Name,isoCode,Population)
      values('Solomon Islands', 'SLB', '724273')
insert into Countries(Name,isoCode,Population)
      values('Somalia', 'SOM', '17597511')
insert into Countries(Name,isoCode,Population)
      values('South Africa', 'ZAF', '59893885')
insert into Countries(Name,isoCode,Population)
      values('South Sudan', 'SSD', '10913164')
insert into Countries(Name,isoCode,Population)
      values('Spain', 'ESP', '47615034')
insert into Countries(Name,isoCode,Population)
      values('Sri Lanka', 'LKA', '22181000')
insert into Countries(Name,isoCode,Population)
      values('St. Kitts and Nevis', 'KNA', '47657')
insert into Countries(Name,isoCode,Population)
      values('St. Lucia', 'LCA', '179857')
insert into Countries(Name,isoCode,Population)
      values('St. Martin (French part)', 'MAF', '31791')
insert into Countries(Name,isoCode,Population)
      values('St. Vincent and the Grenadines', 'VCT', '103948')
insert into Countries(Name,isoCode,Population)
      values('Sudan', 'SDN', '46874204')
insert into Countries(Name,isoCode,Population)
      values('Suriname', 'SUR', '618040')
insert into Countries(Name,isoCode,Population)
      values('Sweden', 'SWE', '10486941')
insert into Countries(Name,isoCode,Population)
      values('Switzerland', 'CHE', '8769741')
insert into Countries(Name,isoCode,Population)
      values('Syrian Arab Republic', 'SYR', '22125249')
insert into Countries(Name,isoCode,Population)
      values('Tajikistan', 'TJK', '9952787')
insert into Countries(Name,isoCode,Population)
      values('Tanzania', 'TZA', '65497748')
insert into Countries(Name,isoCode,Population)
      values('Thailand', 'THA', '71697030')
insert into Countries(Name,isoCode,Population)
      values('Timor-Leste', 'TLS', '1341296')
insert into Countries(Name,isoCode,Population)
      values('Togo', 'TGO', '8848699')
insert into Countries(Name,isoCode,Population)
      values('Tonga', 'TON', '106858')
insert into Countries(Name,isoCode,Population)
      values('Trinidad and Tobago', 'TTO', '1531044')
insert into Countries(Name,isoCode,Population)
      values('Tunisia', 'TUN', '12356117')
insert into Countries(Name,isoCode,Population)
      values('Turkiye', 'TUR', '85341241')
insert into Countries(Name,isoCode,Population)
      values('Turkmenistan', 'TKM', '6430770')
insert into Countries(Name,isoCode,Population)
      values('Turks and Caicos Islands', 'TCA', '45703')
insert into Countries(Name,isoCode,Population)
      values('Tuvalu', 'TUV', '11312')
insert into Countries(Name,isoCode,Population)
      values('Uganda', 'UGA', '47249585')
insert into Countries(Name,isoCode,Population)
      values('Ukraine', 'UKR', '38000000')
insert into Countries(Name,isoCode,Population)
      values('United Arab Emirates', 'ARE', '9441129')
insert into Countries(Name,isoCode,Population)
      values('United Kingdom', 'GBR', '66971411')
insert into Countries(Name,isoCode,Population)
      values('United States', 'USA', '333287557')
insert into Countries(Name,isoCode,Population)
      values('Uruguay', 'URY', '3422794')
insert into Countries(Name,isoCode,Population)
      values('Uzbekistan', 'UZB', '35648100')
insert into Countries(Name,isoCode,Population)
      values('Vanuatu', 'VUT', '326740')
insert into Countries(Name,isoCode,Population)
      values('Venezuela, RB', 'VEN', '28301696')
insert into Countries(Name,isoCode,Population)
      values('Vietnam', 'VNM', '98186856')
insert into Countries(Name,isoCode,Population)
      values('Virgin Islands (U.S.)', 'VIR', '105413')
insert into Countries(Name,isoCode,Population)
      values('West Bank and Gaza', 'PSE', '5043612')
insert into Countries(Name,isoCode,Population)
      values('Yemen, Rep.', 'YEM', '33696614')
insert into Countries(Name,isoCode,Population)
      values('Zambia', 'ZMB', '20017675')
insert into Countries(Name,isoCode,Population)
      values('Zimbabwe', 'ZWE', '16320537')

-- this Inserts gonna set the data for the Restaurant(s) table.

insert into Restaurants (Name, Type) 
values ('Serena', 'Asiática');
insert into Restaurants (Name, Type) 
values ('Le Bristo', 'Francesa');
insert into Restaurants (Name, Type) 
values ('Bocaccio Italian Restaurant', 'Italiana');
insert into Restaurants (Name, Type) 
values ('Mirazur', 'Internacional');
insert into Restaurants (Name, Type) 
values ('Noma', 'Nórdica');
insert into Restaurants (Name, Type) 
values ('Asador Etxebarri', 'Parrilla');
insert into Restaurants (Name, Type) 
values ('Central Restaurante', 'Peruana');
insert into Restaurants (Name, Type) 
values ('Mugaritz', 'Cocina Urbana');
insert into Restaurants (Name, Type) 
values ('Disfrutar', 'Mediterránea');
insert into Restaurants (Name, Type) 
values ('Den', 'Japonesa');

--this Inserts gonna set the data for the Hotel(s) table

insert into Hotels (Name, Stars) values ('kyber', '4');
insert into Hotels (Name, Stars) values ('Safi landmark', '5');
insert into Hotels (Name, Stars) values ('Colombo', '4.5');
insert into Hotels (Name, Stars) values ('TULEMAR BUNGALOWS & VILLAS', '5');
insert into Hotels (Name, Stars) values ('COLLINE DE FRANCE', '4.8');
insert into Hotels (Name, Stars) values ('IKOS ARIA', '4.4');
insert into Hotels (Name, Stars) values ('ROMANCE ISTAMBUL HOTEL', '4.0');
insert into Hotels (Name, Stars) values ('THE OMNIA', '4.7');
insert into Hotels (Name, Stars) values ('KAYAKAPI CAVES', '5');
insert into Hotels (Name, Stars) values ('SIX SENSES LAAMU', '3.8');


